package com.tema1.player;

import com.tema1.goods.Goods;
import com.tema1.goods.GoodsType;
import com.tema1.goods.IllegalGoods;

import java.util.ArrayList;
import java.util.Map;

public class Stall {
    private ArrayList<Goods> goodsList;

    public Stall() {
        goodsList = new ArrayList<>();
    }

    /**
     * Adds all the items to the players stall.
     * @param items The items to be added
     */
    public void addItems(final ArrayList<Goods> items) {
        for (Goods item : items) {
            goodsList.add(item);
            if (item.getType() == GoodsType.Illegal) {
                // Add the bonuses
                for (Map.Entry<Goods, Integer> entry
                        : ((IllegalGoods) item).getIllegalBonus().entrySet()) {
                    for (int i = 0; i < entry.getValue(); i++) {
                        goodsList.add(entry.getKey());
                    }
                }

            }
        }
    }

    /**
     * Computes the profit generated by the items on the stall.
     * @return The profit generated
     */
    public int getScore() {
        int score = 0;
        for (Goods item : goodsList) {
            score += item.getProfit();
        }
        return score;
    }
}
