package com.tema1.player;

import com.tema1.goods.Goods;

import java.util.ArrayList;

public class Stall {
    private ArrayList<Goods> goodsList;

    public Stall() {
        goodsList = new ArrayList<>();
    }

    /**
     * Adds all the items to the players stall.
     * @param items The items to be added
     */
    public void addItems(final ArrayList<Goods> items) {
        goodsList.addAll(items);
    }

    /**
     * Computes the profit generated by the items on the stall.
     * @return The profit generated
     */
    public int getScore() {
        // TODO
        int score = 0;
        score = goodsList.get(0).getProfit();
        return score;
    }
}
