name: Github Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - uses: actions/setup-java@v1
    with:
      java-version: '13' // The JDK version to make available on the path. Takes a whole or semver Jdk version, or 1.x syntax (e.g. 1.8 => Jdk 8.x)
      architecture: x64 // (x64 or x86) - defaults to x64
    - run: bash ./src/tema-checker.sh